# Trabalho final de Aprendizagem de máquina
# Análise da aprendizagem de máquina do smart defender

##Componentes:

### Frederico 

### Gilles

### Jusciaane 

### Lucileide


##1.  Carregar módulos

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFECV
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import linear_model
from sklearn.linear_model import Perceptron
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import SGDClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix

## 2. Carregar dataset

In [0]:
data = pd.read_csv("dataset_descriptor.csv")

print(data.columns)
print(data.shape)

Index(['ip_proto', 'ip_len_mean', 'ip_len_median', 'ip_len_var', 'ip_len_std',
       'ip_len_entropy', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte',
       'ip_ttl_mean', 'ip_ttl_median', 'ip_ttl_var', 'ip_ttl_std',
       'ip_ttl_entropy', 'ip_ttl_cv', 'ip_ttl_cvq', 'ip_ttl_rte', 'sport_mean',
       'sport_median', 'sport_var', 'sport_std', 'sport_entropy', 'sport_cv',
       'sport_cvq', 'sport_rte', 'dport_mean', 'dport_median', 'dport_var',
       'dport_std', 'dport_entropy', 'dport_cv', 'dport_cvq', 'dport_rte',
       'tcp_seq_median', 'tcp_seq_mean', 'tcp_seq_var', 'tcp_seq_std',
       'tcp_seq_entropy', 'tcp_seq_cv', 'tcp_seq_cvq', 'tcp_seq_rte',
       'tcp_ack_mean', 'tcp_ack_median', 'tcp_ack_var', 'tcp_ack_std',
       'tcp_ack_entropy', 'tcp_ack_cv', 'tcp_ack_cvq', 'tcp_ack_rte',
       'tcp_dataofs_mean', 'tcp_dataofs_median', 'tcp_dataofs_var',
       'tcp_dataofs_std', 'tcp_dataofs_entropy', 'tcp_dataofs_cv',
       'tcp_dataofs_cvq', 'tcp_dataofs_rte', 'tcp_flags_mean',

## 3. Visualizar dados

In [0]:
# Visualização dos dados
data.head(5)

ip_proto  ip_len_mean  ip_len_median  ip_len_var  ip_len_std  \
0     0.006     0.262967       0.110169    0.089055    0.298422   
1     0.006     0.263974       0.111588    0.088491    0.297474   
2     0.006     0.267898       0.112069    0.092387    0.303952   
3     0.006     0.262924       0.111349    0.087759    0.296242   
4     0.006     0.263095       0.111111    0.087983    0.296620   

   ip_len_entropy  ip_len_cv  ip_len_cvq  ip_len_rte  ip_ttl_mean     ...      \
0        0.003505        1.0    0.772429    0.128257     0.262967     ...       
1        0.003491        1.0    0.770419    0.126253     0.263974     ...       
2        0.003531        1.0    0.772926    0.132265     0.267898     ...       
3        0.003518        1.0    0.767961    0.132265     0.262924     ...       
4        0.003556        1.0    0.770925    0.142285     0.263095     ...       

   tcp_window_median  tcp_window_var  tcp_window_std  tcp_window_entropy  \
0           0.008596        0.157934        0.397409            0.002115   
1           0.008596        0.157934        0.397409            0.002115   
2           0.008596        0.157933        0.397408            0.002115   
3           0.008596        0.157934        0.397409            0.002115   
4           0.008596        0.157934        0.397409            0.002115   

   tcp_window_cv  tcp_window_cvq  tcp_window_rte      Label1  Label2  \
0            1.0        0.984437        0.006012  http_flood  attack   
1            1.0        0.984437        0.006012  http_flood  attack   
2            1.0        0.984437        0.006012  http_flood  attack   
3            1.0        0.984437        0.006012  http_flood  attack   
4            1.0        0.984437        0.006012  http_flood  attack   

       Label3  
0  http_flood  
1  http_flood  
2  http_flood  
3  http_flood  
4  http_flood  

[5 rows x 76 columns]

In [0]:
# Tipos de dados das colunas
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45500 entries, 0 to 45499
Data columns (total 76 columns):
ip_proto               45500 non-null float64
ip_len_mean            45500 non-null float64
ip_len_median          45500 non-null float64
ip_len_var             45500 non-null float64
ip_len_std             45500 non-null float64
ip_len_entropy         45500 non-null float64
ip_len_cv              45500 non-null float64
ip_len_cvq             45500 non-null float64
ip_len_rte             45500 non-null float64
ip_ttl_mean            45500 non-null float64
ip_ttl_median          45500 non-null float64
ip_ttl_var             45500 non-null float64
ip_ttl_std             45500 non-null float64
ip_ttl_entropy         45500 non-null float64
ip_ttl_cv              45500 non-null float64
ip_ttl_cvq             45500 non-null float64
ip_ttl_rte             45500 non-null float64
sport_mean             45500 non-null float64
sport_median           45500 non-null float64
sport_var        

In [0]:
# quantidade de dados categóricos em Label 1
data.Label1.value_counts()

normal               23088
udp_flood             6894
tcp_syn_flood         5714
tcp_syn_ack_flood     5274
tcp_fin_flood         2000
tcp_ack_flood         2000
http_flood             347
http_slow_body          46
http_slow_range         46
http_slow_read          46
http_slow_headers       45
Name: Label1, dtype: int64

In [0]:
# quantidade de dados categóricos em Label 2
data.Label2.value_counts()

normal    23088
attack    22412
Name: Label2, dtype: int64

In [0]:
# quantidade de dados categóricos em Label 3
data.Label3.value_counts()

normal        23088
tcp_flood     14988
udp_flood      6894
http_flood      347
http_slow       183
Name: Label3, dtype: int64

In [0]:
# Descrição dos dados numéricos
data.describe()

ip_proto   ip_len_mean  ip_len_median    ip_len_var    ip_len_std  \
count  45500.000000  45500.000000   45500.000000  45500.000000  45500.000000   
mean       0.007781      0.745748       0.753272      0.031976      0.112343   
std        0.004052      0.334254       0.377579      0.054293      0.139123   
min        0.006000      0.038782       0.026667      0.000000      0.000000   
25%        0.006000      0.361192       0.276667      0.000000      0.000000   
50%        0.006000      0.985554       1.000000      0.003307      0.057508   
75%        0.006000      1.000000       1.000000      0.034742      0.186392   
max        0.017000      1.000000       1.000000      0.227344      0.476806   

       ip_len_entropy     ip_len_cv    ip_len_cvq    ip_len_rte   ip_ttl_mean  \
count    45500.000000  45500.000000  45500.000000  45500.000000  45500.000000   
mean         0.001188      0.273446      0.237955      0.032237      0.745748   
std          0.001585      0.320556      0.337118      0.045028      0.334254   
min          0.000000      0.000000      0.000000      0.000030      0.038782   
25%          0.000000      0.000000      0.000000      0.002004      0.361192   
50%          0.000060      0.106342      0.000000      0.004269      0.985554   
75%          0.002347      0.545385      0.487179      0.056112      1.000000   
max          0.010203      1.000000      0.948052      0.446894      1.000000   

            ...        tcp_flags_cvq  tcp_flags_rte  tcp_window_mean  \
count       ...         45500.000000   45500.000000     45500.000000   
mean        ...             0.106951       0.005193         0.767043   
std         ...             0.166626       0.004146         0.371137   
min         ...             0.000000       0.000000         0.000000   
25%         ...             0.000000       0.002004         0.717435   
50%         ...             0.000000       0.004008         0.980701   
75%         ...             0.200000       0.008016         1.000000   
max         ...             0.846154       0.016032         1.000000   

       tcp_window_median  tcp_window_var  tcp_window_std  tcp_window_entropy  \
count       45500.000000    45500.000000    45500.000000        45500.000000   
mean            0.786191        0.019787        0.071063            0.001232   
std             0.384125        0.050544        0.121398            0.001773   
min             0.000000        0.000000        0.000000            0.000000   
25%             0.857143        0.000000        0.000000            0.000000   
50%             1.000000        0.000000        0.000000            0.000000   
75%             1.000000        0.008355        0.091405            0.002163   
max             1.000000        0.250477        0.500477            0.010392   

       tcp_window_cv  tcp_window_cvq  tcp_window_rte  
count   45500.000000    45500.000000    45500.000000  
mean        0.106695        0.105045        0.026920  
std         0.214189        0.269163        0.046510  
min         0.000000        0.000000        0.000000  
25%         0.000000        0.000000        0.002004  
50%         0.000000        0.000000        0.002004  
75%         0.100706        0.033506        0.032064  
max         1.000000        1.000000        0.466934  

[8 rows x 73 columns]

In [0]:
#dados faltantes
data.isnull().sum()

ip_proto               0
ip_len_mean            0
ip_len_median          0
ip_len_var             0
ip_len_std             0
ip_len_entropy         0
ip_len_cv              0
ip_len_cvq             0
ip_len_rte             0
ip_ttl_mean            0
ip_ttl_median          0
ip_ttl_var             0
ip_ttl_std             0
ip_ttl_entropy         0
ip_ttl_cv              0
ip_ttl_cvq             0
ip_ttl_rte             0
sport_mean             0
sport_median           0
sport_var              0
sport_std              0
sport_entropy          0
sport_cv               0
sport_cvq              0
sport_rte              0
dport_mean             0
dport_median           0
dport_var              0
dport_std              0
dport_entropy          0
                      ..
tcp_ack_cv             0
tcp_ack_cvq            0
tcp_ack_rte            0
tcp_dataofs_mean       0
tcp_dataofs_median     0
tcp_dataofs_var        0
tcp_dataofs_std        0
tcp_dataofs_entropy    0
tcp_dataofs_cv         0


## 4. Separar Features e Alvo

In [0]:
columns = ["ip_proto","ip_len_mean","ip_len_median","ip_len_var",
               "ip_len_std","ip_len_entropy","ip_len_cv","ip_len_cvq",
               "ip_len_rte", "sport_mean","sport_median","sport_var","sport_std",
               "sport_entropy","sport_cv","sport_cvq","sport_rte",
               "dport_mean","dport_median","dport_var","dport_std",
               "dport_entropy","dport_cv","dport_cvq","dport_rte",
               "tcp_flags_mean","tcp_flags_median","tcp_flags_var",
               "tcp_flags_std","tcp_flags_entropy","tcp_flags_cv",
               "tcp_flags_cvq","tcp_flags_rte","Label2"]

data = data[columns]

## 5. Transformar a label categórica em numérica

In [0]:
for i in range(0,len(data)):
  if data.loc[i,'Label2']=="normal":
    data.loc[i,'Label2']=0
  else: #data[i,'Label2']=='attack' :
    data.loc[i,'Label2']=1
    

## 6. Divisão dos dados

In [0]:
train, test= train_test_split(data, 
                              test_size=0.3, 
                              random_state=35)

print("data has {} instances\n {} train instances\n {} test intances".
      format(len(data),len(train),len(test)))


data has 45500 instances
 31850 train instances
 13650 test intances


In [0]:
X_train =train.drop('Label2', axis=1)
y_train =train['Label2']
X_test =test.drop('Label2', axis=1)
y_test =test['Label2']

## 7. Selecionar Features

In [0]:
def select_features(df,index):
    
    # index
    # 0 - Random forest
    # 1 - Logistic regression
    # 2 - SGD
    # 3 - Perceptron
    # 4 - AdaBoost

       
    clf_rf  = RandomForestClassifier(random_state=1, n_estimators=100)
    clf_lr  = LogisticRegression()
    clf_sgd = linear_model.SGDClassifier()
    clf_p   = Perceptron()
    clf_ada = AdaBoostClassifier()
    clf_svc = SVC()
    clf_knc = KNeighborsClassifier()
    clfs = [clf_rf,clf_lr,clf_sgd,clf_p, clf_ada]
    
    all_X = df.drop(["Label2"],axis=1)
    all_y = df["Label2"]
    
    selector = RFECV(clfs[index],cv=10,n_jobs=-1)
    selector.fit(all_X,all_y)
    
    best_columns = list(all_X.columns[selector.support_])
    print("Best Columns \n"+"-"*12+"\n{}\n".format(best_columns))
    
    return best_columns

#cols_rf = select_features(X_train,0)
#cols_lr = select_features(X_train,1)  
#cols_sgd = select_features(X_train,2)
#cols_p = select_features(X_train,3)
#cols_ada = select_features(X_train,4)
#cols_svc = select_features(X_train,5)
#cols_knc = select_features(X_train,6)

In [0]:
%time cols_rf = select_features(train,0)

In [0]:
%time cols_lr = select_features(train,1)  

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

Best Columns 
------------
['ip_len_mean', 'ip_len_median', 'ip_len_std', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte', 'sport_entropy', 'sport_rte', 'dport_mean', 'dport_std', 'dport_cv', 'tcp_flags_mean', 'tcp_flags_median', 'tcp_flags_var', 'tcp_flags_std', 'tcp_flags_cvq']

CPU times: user 6.18 s, sys: 41.1 ms, total: 6.22 s
Wall time: 1min


In [0]:
%time cols_sgd = select_features(train,2)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=No

Best Columns 
------------
['ip_proto', 'ip_len_mean', 'ip_len_median', 'ip_len_var', 'ip_len_std', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte', 'sport_var', 'sport_entropy', 'sport_cvq', 'sport_rte', 'dport_std', 'dport_cv', 'dport_cvq', 'dport_rte', 'tcp_flags_var', 'tcp_flags_std', 'tcp_flags_cvq', 'tcp_flags_rte']

CPU times: user 810 ms, sys: 23 ms, total: 833 ms
Wall time: 16.9 s


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [0]:
%time cols_p = select_features(train,3)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If to

Best Columns 
------------
['ip_len_mean', 'ip_len_median', 'ip_len_var', 'ip_len_std', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte', 'sport_mean', 'sport_var', 'sport_std', 'sport_entropy', 'sport_cv', 'sport_rte', 'dport_mean', 'dport_cv', 'dport_rte', 'tcp_flags_mean', 'tcp_flags_median', 'tcp_flags_var', 'tcp_flags_std', 'tcp_flags_cv', 'tcp_flags_cvq']

CPU times: user 852 ms, sys: 15 ms, total: 867 ms
Wall time: 16.3 s


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in Perceptron in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [0]:
%time cols_ada = select_features(train,4)

Best Columns 
------------
['ip_len_std', 'ip_len_entropy', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte', 'sport_median', 'sport_entropy', 'sport_rte', 'dport_median', 'dport_cv', 'dport_rte', 'tcp_flags_mean', 'tcp_flags_median', 'tcp_flags_std', 'tcp_flags_cv', 'tcp_flags_cvq', 'tcp_flags_rte']

CPU times: user 1min, sys: 61.9 ms, total: 1min
Wall time: 9min 28s


In [0]:
print(cols_rf)
print(cols_lr)
print(cols_sgd)
print(cols_p)
print(cols_ada)
#print(cols_svc)
#print(cols_knc)

['ip_len_mean', 'ip_len_median', 'ip_len_var', 'ip_len_std', 'ip_len_entropy', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte', 'sport_mean', 'sport_median', 'sport_entropy', 'sport_cvq', 'sport_rte', 'dport_mean', 'dport_median', 'dport_var', 'dport_std', 'dport_entropy', 'dport_cv', 'dport_rte', 'tcp_flags_mean', 'tcp_flags_median', 'tcp_flags_var', 'tcp_flags_std', 'tcp_flags_entropy', 'tcp_flags_cv', 'tcp_flags_cvq', 'tcp_flags_rte']
['ip_len_mean', 'ip_len_median', 'ip_len_std', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte', 'sport_entropy', 'sport_rte', 'dport_mean', 'dport_std', 'dport_cv', 'tcp_flags_mean', 'tcp_flags_median', 'tcp_flags_var', 'tcp_flags_std', 'tcp_flags_cvq']
['ip_proto', 'ip_len_mean', 'ip_len_median', 'ip_len_var', 'ip_len_std', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte', 'sport_var', 'sport_entropy', 'sport_cvq', 'sport_rte', 'dport_std', 'dport_cv', 'dport_cvq', 'dport_rte', 'tcp_flags_var', 'tcp_flags_std', 'tcp_flags_cvq', 'tcp_flags_rte']
['ip_len_mean', 'ip_len_median'

## 8. Escolha do melhores parâmetros e modelos

In [0]:
def select_model(df,features):
    
    #all_X = df[features]
    #all_y = df["Survived"]

    # List of dictionaries, each containing a model name,
    # it's estimator and a dict of hyperparameters
    models = [
        {
            "name": "LogisticRegression",
            "estimator": LogisticRegression(),
            "hyperparameters":
                {
                    "solver": ["newton-cg", "lbfgs", "liblinear"]
                }
        },
        #{
        #    "name": "KNeighborsClassifier",
        #    "estimator": KNeighborsClassifier(),
        #    "hyperparameters":
        #        {
        #            "n_neighbors": range(1,5,2),
        #            "weights": ["distance", "uniform"],
        #            "algorithm": ["ball_tree", "kd_tree", "brute"],
        #            "p": [1,2]
        #        }
        #},
        {
            "name": "RandomForestClassifier",
            "estimator": RandomForestClassifier(random_state=1),
            "hyperparameters":
                {
                    "n_estimators": [200],
                    "criterion": ["entropy", "gini"],
                    "max_depth": [10,20],
                    "max_features": ["log2", "sqrt"],
                    "min_samples_leaf": [1],
                    "min_samples_split": [2]
                }
        },
       # {
       #     "name":"SVC",
       #     "estimator":SVC(),
       #     "hyperparameters":
       #         {
       #           "kernel": ['rbf'],  
       #           "C": [0.001, 0.01, 0.1, 1, 10],
       #           "gamma": [0.001, 0.01, 0.1, 1]
       #         }
       # },
        {
            # reference
            # https://github.com/UltravioletAnalytics/kaggle-titanic/blob/master/sgdclassifier.py
            "name":"SGDC",
            "estimator": SGDClassifier(),
            "hyperparameters":
            {
                "loss": ["log"],
                "alpha": [0.001],
                "penalty": ["elasticnet"],
                "l1_ratio": [0.8],
                "shuffle": [True],
                "learning_rate": ['optimal'],
                "max_iter":[1000]
            }
        },
        {
            "name":"Perceptron",
            "estimator":Perceptron(),
            "hyperparameters":
                {
                  "tol": [1e-3] ,  
                  "random_state":[0]
                }
        },
        {
            "name":" GradientBoosting",
            "estimator": GradientBoostingClassifier(),
            "hyperparameters":
                {
                  "n_estimators": [100,150,200,250,500],
                  "max_depth": [3,4,7,8,9,50]
                }
        },
        #{
        #    "name":" GaussianNB",
        #    "estimator": GaussianNB(),
        #    "hyperparameters":
        #        {
        #        }
        #},        
        {
            "name":" Tree",
            "estimator": tree.DecisionTreeClassifier(),
            "hyperparameters":
                {
                  "max_depth":[1, 2,3,4,5,10,15,25]
                }
        }, 
        {
            "name":"AdaBoostClassifier",
            "estimator": AdaBoostClassifier(),
            "hyperparameters":
                {
                  "n_estimators":[50,70,100,150,200,250,300]
                }
        }
    ]

    for model in models:
        print(model['name'])
        print('-'*len(model['name']))

        grid = GridSearchCV(model["estimator"],
                            param_grid=model["hyperparameters"],
                            cv=10)
        grid.fit(X_train,y_train)
        model["best_params"] = grid.best_params_
        model["best_score"] = grid.best_score_
        model["best_model"] = grid.best_estimator_

        print("Best Score: {}".format(model["best_score"]))
        print("Best Parameters: {}\n".format(model["best_params"]))

    return models

In [0]:
%time result_rf = select_model(train,cols_rf)

LogisticRegression
------------------


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local

Best Score: 0.9830455259026688
Best Parameters: {'solver': 'lbfgs'}

RandomForestClassifier
----------------------
Best Score: 0.9998744113029827
Best Parameters: {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}

SGDC
----


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19.

Best Score: 0.9726844583987441
Best Parameters: {'alpha': 0.001, 'l1_ratio': 0.8, 'learning_rate': 'optimal', 'loss': 'log', 'max_iter': 1000, 'penalty': 'elasticnet', 'shuffle': True}

Perceptron
----------
Best Score: 0.9907692307692307
Best Parameters: {'random_state': 0, 'tol': 0.001}

 GradientBoosting
-----------------
Best Score: 0.9999058084772371
Best Parameters: {'max_depth': 8, 'n_estimators': 150}

 Tree
-----
Best Score: 0.9998430141287284
Best Parameters: {'max_depth': 10}

AdaBoostClassifier
------------------
Best Score: 1.0
Best Parameters: {'n_estimators': 150}

CPU times: user 52min 48s, sys: 10.2 s, total: 52min 58s
Wall time: 52min 43s


In [0]:
%time result_lr = select_model(train,cols_lr)

LogisticRegression
------------------


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local

Best Score: 0.9830455259026688
Best Parameters: {'solver': 'lbfgs'}

RandomForestClassifier
----------------------
Best Score: 0.9998744113029827
Best Parameters: {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}

SGDC
----


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19.

Best Score: 0.9725588697017269
Best Parameters: {'alpha': 0.001, 'l1_ratio': 0.8, 'learning_rate': 'optimal', 'loss': 'log', 'max_iter': 1000, 'penalty': 'elasticnet', 'shuffle': True}

Perceptron
----------
Best Score: 0.9907692307692307
Best Parameters: {'random_state': 0, 'tol': 0.001}

 GradientBoosting
-----------------
Best Score: 0.9999058084772371
Best Parameters: {'max_depth': 7, 'n_estimators': 150}

 Tree
-----
Best Score: 0.9998430141287284
Best Parameters: {'max_depth': 4}

AdaBoostClassifier
------------------
Best Score: 1.0
Best Parameters: {'n_estimators': 150}

CPU times: user 57min 14s, sys: 11.5 s, total: 57min 26s
Wall time: 1h 7min 49s


In [0]:
%time result_sgd = select_model(train,cols_sgd)

LogisticRegression
------------------


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/usr/local

Best Score: 0.9830455259026688
Best Parameters: {'solver': 'lbfgs'}

RandomForestClassifier
----------------------
Best Score: 0.9998744113029827
Best Parameters: {'criterion': 'entropy', 'max_depth': 10, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}

SGDC
----


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19.

Best Score: 0.9727158555729984
Best Parameters: {'alpha': 0.001, 'l1_ratio': 0.8, 'learning_rate': 'optimal', 'loss': 'log', 'max_iter': 1000, 'penalty': 'elasticnet', 'shuffle': True}

Perceptron
----------
Best Score: 0.9907692307692307
Best Parameters: {'random_state': 0, 'tol': 0.001}

 GradientBoosting
-----------------
Best Score: 0.9999058084772371
Best Parameters: {'max_depth': 7, 'n_estimators': 150}

 Tree
-----
Best Score: 0.9998430141287284
Best Parameters: {'max_depth': 4}

AdaBoostClassifier
------------------
Best Score: 1.0
Best Parameters: {'n_estimators': 150}

CPU times: user 1h 18min 58s, sys: 14.5 s, total: 1h 19min 13s
Wall time: 1h 51min 3s


In [0]:
%time result_p = select_model(train,cols_p)

In [0]:
%time result_ada = select_model(train,cols_ada)

## 9. Teste 

Com colunas selecionadas pelo 1. Random forest




In [0]:
result_rf

[{'best_model': LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
            intercept_scaling=1, max_iter=100, multi_class='warn',
            n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
            tol=0.0001, verbose=0, warm_start=False),
  'best_params': {'solver': 'lbfgs'},
  'best_score': 0.9830455259026688,
  'estimator': LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
            intercept_scaling=1, max_iter=100, multi_class='warn',
            n_jobs=None, penalty='l2', random_state=None, solver='warn',
            tol=0.0001, verbose=0, warm_start=False),
  'hyperparameters': {'solver': ['newton-cg', 'lbfgs', 'liblinear']},
  'name': 'LogisticRegression'},
 {'best_model': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
              max_depth=10, max_features='log2', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_

In [0]:
#result_rf[0]

model0= result_rf[0]["best_model"]
p0=model0.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc0=accuracy_score(y_test, p0)
print(acc0)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m0=confusion_matrix(y_test, p0)
print(m0)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k0=cohen_kappa_score(y_test,p0)
print(k0)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc0=roc_auc_score(y_test, p0)
print(auc0)

0.9848351648351649
[[6888  110]
 [  97 6555]]
0.9696522958966398
0.9848495713146803


In [0]:
#result_rf[1]

model1= result_rf[1]["best_model"]
p1=model1.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc1=accuracy_score(y_test, p1)
print(acc1)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m1=confusion_matrix(y_test, p1)
print(m1)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k1=cohen_kappa_score(y_test,p1)
print(k1)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc1=roc_auc_score(y_test, p1)
print(auc1)

1.0
[[6998    0]
 [   0 6652]]
1.0
1.0


In [0]:
#result_rf[2]

model2= result_rf[2]["best_model"]
p2=model2.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc2=accuracy_score(y_test, p2)
print(acc2)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m2=confusion_matrix(y_test, p2)
print(m2)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k2=cohen_kappa_score(y_test,p2)
print(k2)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc2=roc_auc_score(y_test, p2)
print(auc2)

0.9743589743589743
[[6745  253]
 [  97 6555]]
0.9487147106756102
0.97463236639899


In [0]:
#result_rf[3]

model3= result_rf[3]["best_model"]
p3=model3.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc3=accuracy_score(y_test, p3)
print(acc3)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m3=confusion_matrix(y_test, p3)
print(m3)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k3=cohen_kappa_score(y_test,p3)
print(k3)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc3=roc_auc_score(y_test, p3)
print(auc3)

0.9875457875457876
[[6828  170]
 [   0 6652]]
0.9750912975595204
0.9878536724778508


In [0]:
#result_rf[4]

model4= result_rf[4]["best_model"]
p4=model4.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc4=accuracy_score(y_test, p4)
print(acc4)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m4=confusion_matrix(y_test, p4)
print(m4)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k4=cohen_kappa_score(y_test,p4)
print(k4)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc4=roc_auc_score(y_test, p4)
print(auc4)

1.0
[[6998    0]
 [   0 6652]]
1.0
1.0


In [0]:
#result_rf[5]

model5= result_rf[5]["best_model"]
p5=model5.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc5=accuracy_score(y_test, p5)
print(acc5)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m5=confusion_matrix(y_test, p5)
print(m5)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k5=cohen_kappa_score(y_test,p5)
print(k5)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc5=roc_auc_score(y_test, p5)
print(auc5)

0.99992673992674
[[6997    1]
 [   0 6652]]
0.9998533861956476
0.9999285510145757


In [0]:
#result_rf[6]

model6= result_rf[6]["best_model"]
p6=model6.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc6=accuracy_score(y_test, p6)
print(acc6)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m6=confusion_matrix(y_test, p6)
print(m6)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k6=cohen_kappa_score(y_test,p6)
print(k6)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc6=roc_auc_score(y_test, p6)
print(auc6)

1.0
[[6998    0]
 [   0 6652]]
1.0
1.0


Com colunas selecionadas pelo 2. Logistic

In [0]:
result_lr

[{'best_model': LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
            intercept_scaling=1, max_iter=100, multi_class='warn',
            n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
            tol=0.0001, verbose=0, warm_start=False),
  'best_params': {'solver': 'lbfgs'},
  'best_score': 0.9830455259026688,
  'estimator': LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
            intercept_scaling=1, max_iter=100, multi_class='warn',
            n_jobs=None, penalty='l2', random_state=None, solver='warn',
            tol=0.0001, verbose=0, warm_start=False),
  'hyperparameters': {'solver': ['newton-cg', 'lbfgs', 'liblinear']},
  'name': 'LogisticRegression'},
 {'best_model': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
              max_depth=10, max_features='log2', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_

In [0]:
#result_lr[0]
print("1. Logistic")

model0= result_lr[0]["best_model"]
p0=model0.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc0=accuracy_score(y_test, p0)
print(acc0)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m0=confusion_matrix(y_test, p0)
print(m0)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k0=cohen_kappa_score(y_test,p0)
print(k0)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc0=roc_auc_score(y_test, p0)
print(auc0)

#result_lr[1]
print("2. Randon")

model1= result_lr[1]["best_model"]
p1=model1.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc1=accuracy_score(y_test, p1)
print(acc1)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m1=confusion_matrix(y_test, p1)
print(m1)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k1=cohen_kappa_score(y_test,p1)
print(k1)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc1=roc_auc_score(y_test, p1)
print(auc1)

#result_lr[2]
print("3. SGDC")

model2= result_lr[2]["best_model"]
p2=model2.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc2=accuracy_score(y_test, p2)
print(acc2)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m2=confusion_matrix(y_test, p2)
print(m2)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k2=cohen_kappa_score(y_test,p2)
print(k2)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc2=roc_auc_score(y_test, p2)
print(auc2)

#result_lr[3]
print("4. Perceptron")

model3= result_lr[3]["best_model"]
p3=model3.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc3=accuracy_score(y_test, p3)
print(acc3)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m3=confusion_matrix(y_test, p3)
print(m3)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k3=cohen_kappa_score(y_test,p3)
print(k3)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc3=roc_auc_score(y_test, p3)
print(auc3)

#result_lr[4]
print("5. Gradient")

model4= result_lr[4]["best_model"]
p4=model4.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc4=accuracy_score(y_test, p4)
print(acc4)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m4=confusion_matrix(y_test, p4)
print(m4)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k4=cohen_kappa_score(y_test,p4)
print(k4)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc4=roc_auc_score(y_test, p4)
print(auc4)

#result_lr[5]
print("6. Tree")

model5= result_lr[5]["best_model"]
p5=model5.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc5=accuracy_score(y_test, p5)
print(acc5)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m5=confusion_matrix(y_test, p5)
print(m5)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k5=cohen_kappa_score(y_test,p5)
print(k5)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc5=roc_auc_score(y_test, p5)
print(auc5)

#result_lr[6]
print("7. AdaBoost")

model6= result_lr[6]["best_model"]
p6=model6.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc6=accuracy_score(y_test, p6)
print(acc6)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m6=confusion_matrix(y_test, p6)
print(m6)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k6=cohen_kappa_score(y_test,p6)
print(k6)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc6=roc_auc_score(y_test, p6)
print(auc6)

1. Logistic
0.9848351648351649
[[6888  110]
 [  97 6555]]
0.9696522958966398
0.9848495713146803
2. Randon
1.0
[[6998    0]
 [   0 6652]]
1.0
1.0
3. SGDC
0.9743589743589743
[[6745  253]
 [  97 6555]]
0.9487147106756102
0.97463236639899
4. Perceptron
0.9875457875457876
[[6828  170]
 [   0 6652]]
0.9750912975595204
0.9878536724778508
5. Gradient
1.0
[[6998    0]
 [   0 6652]]
1.0
1.0
6. Tree
0.99992673992674
[[6997    1]
 [   0 6652]]
0.9998533861956476
0.9999285510145757
7. AdaBoost
1.0
[[6998    0]
 [   0 6652]]
1.0
1.0


Com colunas selecionadas pelo 3. SGD

In [0]:
result_sgd

[{'best_model': LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
            intercept_scaling=1, max_iter=100, multi_class='warn',
            n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
            tol=0.0001, verbose=0, warm_start=False),
  'best_params': {'solver': 'lbfgs'},
  'best_score': 0.9830455259026688,
  'estimator': LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
            intercept_scaling=1, max_iter=100, multi_class='warn',
            n_jobs=None, penalty='l2', random_state=None, solver='warn',
            tol=0.0001, verbose=0, warm_start=False),
  'hyperparameters': {'solver': ['newton-cg', 'lbfgs', 'liblinear']},
  'name': 'LogisticRegression'},
 {'best_model': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
              max_depth=10, max_features='log2', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_

In [0]:
#result_sgd[0]
print("1. Logistic")

model0= result_sgd[0]["best_model"]
p0=model0.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc0=accuracy_score(y_test, p0)
print(acc0)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m0=confusion_matrix(y_test, p0)
print(m0)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k0=cohen_kappa_score(y_test,p0)
print(k0)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc0=roc_auc_score(y_test, p0)
print(auc0)

#result_sgd[1]
print("2. Randon")

model1= result_sgd[1]["best_model"]
p1=model1.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc1=accuracy_score(y_test, p1)
print(acc1)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m1=confusion_matrix(y_test, p1)
print(m1)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k1=cohen_kappa_score(y_test,p1)
print(k1)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc1=roc_auc_score(y_test, p1)
print(auc1)

#result_sgd[2]
print("3. SGDC")

model2= result_sgd[2]["best_model"]
p2=model2.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc2=accuracy_score(y_test, p2)
print(acc2)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m2=confusion_matrix(y_test, p2)
print(m2)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k2=cohen_kappa_score(y_test,p2)
print(k2)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc2=roc_auc_score(y_test, p2)
print(auc2)

#result_sgd[3]
print("4. Perceptron")

model3= result_sgd[3]["best_model"]
p3=model3.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc3=accuracy_score(y_test, p3)
print(acc3)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m3=confusion_matrix(y_test, p3)
print(m3)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k3=cohen_kappa_score(y_test,p3)
print(k3)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc3=roc_auc_score(y_test, p3)
print(auc3)

#result_sgd[4]
print("5. Gradient")

model4= result_sgd[4]["best_model"]
p4=model4.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc4=accuracy_score(y_test, p4)
print(acc4)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m4=confusion_matrix(y_test, p4)
print(m4)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k4=cohen_kappa_score(y_test,p4)
print(k4)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc4=roc_auc_score(y_test, p4)
print(auc4)

#result_sgd[5]
print("6. Tree")

model5= result_sgd[5]["best_model"]
p5=model5.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc5=accuracy_score(y_test, p5)
print(acc5)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m5=confusion_matrix(y_test, p5)
print(m5)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k5=cohen_kappa_score(y_test,p5)
print(k5)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc5=roc_auc_score(y_test, p5)
print(auc5)

#result_sgd[6]
print("7. AdaBoost")

model6= result_sgd[6]["best_model"]
p6=model6.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc6=accuracy_score(y_test, p6)
print(acc6)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m6=confusion_matrix(y_test, p6)
print(m6)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k6=cohen_kappa_score(y_test,p6)
print(k6)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc6=roc_auc_score(y_test, p6)
print(auc6)

1. Logistic
0.9848351648351649
[[6888  110]
 [  97 6555]]
0.9696522958966398
0.9848495713146803
2. Randon
1.0
[[6998    0]
 [   0 6652]]
1.0
1.0
3. SGDC
0.9743589743589743
[[6745  253]
 [  97 6555]]
0.9487147106756102
0.97463236639899
4. Perceptron
0.9875457875457876
[[6828  170]
 [   0 6652]]
0.9750912975595204
0.9878536724778508
5. Gradient
1.0
[[6998    0]
 [   0 6652]]
1.0
1.0
6. Tree
0.99992673992674
[[6997    1]
 [   0 6652]]
0.9998533861956476
0.9999285510145757
7. AdaBoost
1.0
[[6998    0]
 [   0 6652]]
1.0
1.0


Com colunas selecionadas pelo 4. perceptron

In [0]:
result_p

In [0]:
#result_p[0]
print("1. Logistic")

model0= result_p[0]["best_model"]
p0=model0.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc0=accuracy_score(y_test, p0)
print(acc0)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m0=confusion_matrix(y_test, p0)
print(m0)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k0=cohen_kappa_score(y_test,p0)
print(k0)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc0=roc_auc_score(y_test, p0)
print(auc0)

#result_p[1]
print("2. Randon")

model1= result_p[1]["best_model"]
p1=model1.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc1=accuracy_score(y_test, p1)
print(acc1)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m1=confusion_matrix(y_test, p1)
print(m1)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k1=cohen_kappa_score(y_test,p1)
print(k1)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc1=roc_auc_score(y_test, p1)
print(auc1)

#result_p[2]
print("3. SGDC")

model2= result_p[2]["best_model"]
p2=model2.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc2=accuracy_score(y_test, p2)
print(acc2)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m2=confusion_matrix(y_test, p2)
print(m2)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k2=cohen_kappa_score(y_test,p2)
print(k2)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc2=roc_auc_score(y_test, p2)
print(auc2)

#result_p[3]
print("4. Perceptron")

model3= result_p[3]["best_model"]
p3=model3.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc3=accuracy_score(y_test, p3)
print(acc3)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m3=confusion_matrix(y_test, p3)
print(m3)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k3=cohen_kappa_score(y_test,p3)
print(k3)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc3=roc_auc_score(y_test, p3)
print(auc3)

#result_p[4]
print("5. Gradient")

model4= result_p[4]["best_model"]
p4=model4.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc4=accuracy_score(y_test, p4)
print(acc4)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m4=confusion_matrix(y_test, p4)
print(m4)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k4=cohen_kappa_score(y_test,p4)
print(k4)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc4=roc_auc_score(y_test, p4)
print(auc4)

#result_p[5]
print("6. Tree")

model5= result_p[5]["best_model"]
p5=model5.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc5=accuracy_score(y_test, p5)
print(acc5)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m5=confusion_matrix(y_test, p5)
print(m5)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k5=cohen_kappa_score(y_test,p5)
print(k5)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc5=roc_auc_score(y_test, p5)
print(auc5)

#result_p[6]
print("7. AdaBoost")

model6= result_p[6]["best_model"]
p6=model6.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc6=accuracy_score(y_test, p6)
print(acc6)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m6=confusion_matrix(y_test, p6)
print(m6)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k6=cohen_kappa_score(y_test,p6)
print(k6)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc6=roc_auc_score(y_test, p6)
print(auc6)

Com colunas selecionadas pelo 5. AdaBoost

In [0]:
result_ada

In [0]:
#result_ada[0]
print("1. Logistic")

model0= result_ada[0]["best_model"]
p0=model0.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc0=accuracy_score(y_test, p0)
print(acc0)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m0=confusion_matrix(y_test, p0)
print(m0)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k0=cohen_kappa_score(y_test,p0)
print(k0)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc0=roc_auc_score(y_test, p0)
print(auc0)

#result_ada[1]
print("2. Randon")

model1= result_ada[1]["best_model"]
p1=model1.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc1=accuracy_score(y_test, p1)
print(acc1)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m1=confusion_matrix(y_test, p1)
print(m1)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k1=cohen_kappa_score(y_test,p1)
print(k1)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc1=roc_auc_score(y_test, p1)
print(auc1)

#result_ada[2]
print("3. SGDC")

model2= result_ada[2]["best_model"]
p2=model2.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc2=accuracy_score(y_test, p2)
print(acc2)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m2=confusion_matrix(y_test, p2)
print(m2)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k2=cohen_kappa_score(y_test,p2)
print(k2)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc2=roc_auc_score(y_test, p2)
print(auc2)

#result_ada[3]
print("4. Perceptron")

model3= result_ada[3]["best_model"]
p3=model3.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc3=accuracy_score(y_test, p3)
print(acc3)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m3=confusion_matrix(y_test, p3)
print(m3)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k3=cohen_kappa_score(y_test,p3)
print(k3)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc3=roc_auc_score(y_test, p3)
print(auc3)

#result_ada[4]
print("5. Gradient")

model4= result_ada[4]["best_model"]
p4=model4.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc4=accuracy_score(y_test, p4)
print(acc4)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m4=confusion_matrix(y_test, p4)
print(m4)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k4=cohen_kappa_score(y_test,p4)
print(k4)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc4=roc_auc_score(y_test, p4)
print(auc4)

#result_ada[5]
print("6. Tree")

model5= result_ada[5]["best_model"]
p5=model5.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc5=accuracy_score(y_test, p5)
print(acc5)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m5=confusion_matrix(y_test, p5)
print(m5)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k5=cohen_kappa_score(y_test,p5)
print(k5)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc5=roc_auc_score(y_test, p5)
print(auc5)

#result_ada[6]
print("7. AdaBoost")

model6= result_ada[6]["best_model"]
p6=model6.predict(X_test)

#Acurácia
from sklearn.metrics import accuracy_score
acc6=accuracy_score(y_test, p6)
print(acc6)

#Matriz de confusão
from sklearn.metrics import confusion_matrix
m6=confusion_matrix(y_test, p6)
print(m6)

#Índice Kappa
from sklearn.metrics import cohen_kappa_score
k6=cohen_kappa_score(y_test,p6)
print(k6)

#ROC AUC
from sklearn.metrics import roc_auc_score
auc6=roc_auc_score(y_test, p6)
print(auc6)

## 10. Tempo de execução

In [0]:
colunas_logistic=['ip_len_mean', 'ip_len_median', 'ip_len_std', 'ip_len_cv', 'ip_len_cvq', 'ip_len_rte', 'sport_entropy', 'sport_rte', 'dport_mean', 'dport_std', 'dport_cv', 'tcp_flags_mean', 'tcp_flags_median', 'tcp_flags_var', 'tcp_flags_std', 'tcp_flags_cvq']

In [0]:
# logistic
log=LogisticRegression(solver= 'lbfgs')
%time log.fit(X_train[colunas_logistic], y_train)

CPU times: user 539 ms, sys: 222 ms, total: 761 ms
Wall time: 405 ms


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
# randon
randon=RandomForestClassifier(random_state=1,criterion= 'entropy', max_depth= 10,max_features= 'log2', min_samples_leaf= 1, min_samples_split= 2, n_estimators= 200)
%time randon.fit(X_train[colunas_logistic], y_train)

CPU times: user 5.6 s, sys: 2.94 ms, total: 5.6 s
Wall time: 5.61 s


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=10, max_features='log2', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [0]:
# SGDC
SGDC=SGDClassifier(alpha= 0.001, l1_ratio= 0.8, learning_rate= 'optimal', loss= 'log', max_iter= 1000, penalty= 'elasticnet', shuffle= True)
%time SGDC.fit(X_train[colunas_logistic], y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


CPU times: user 11.9 s, sys: 4.95 ms, total: 11.9 s
Wall time: 11.9 s


SGDClassifier(alpha=0.001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.8, learning_rate='optimal', loss='log', max_iter=1000,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='elasticnet',
       power_t=0.5, random_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
#perceptron
percep=Perceptron(random_state= 0, tol= 0.001)
%time percep.fit(X_train[colunas_logistic], y_train)

CPU times: user 62.9 ms, sys: 999 µs, total: 63.9 ms
Wall time: 67.3 ms


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
      fit_intercept=True, max_iter=None, n_iter=None, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=0.001,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
#gradient
grad=GradientBoostingClassifier(max_depth= 7, n_estimators= 150)
%time grad.fit(X_train[colunas_logistic], y_train)

CPU times: user 3.01 s, sys: 4.04 ms, total: 3.02 s
Wall time: 3.02 s


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=7,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=150,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [0]:
#tree
tree=tree.DecisionTreeClassifier(max_depth= 4)
%time tree.fit(X_train[colunas_logistic], y_train)

CPU times: user 114 ms, sys: 4 ms, total: 118 ms
Wall time: 121 ms


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [0]:
#adaboost
ada=AdaBoostClassifier(n_estimators= 150)
%time ada.fit(X_train[colunas_logistic], y_train)

CPU times: user 6.52 s, sys: 8.96 ms, total: 6.53 s
Wall time: 6.54 s


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=150, random_state=None)